name: Test CI Pipeline

on:
  push:
    branches: ["**"] # Se déclenche sur toutes ls branches après un push

jobs:
  hello-world-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher message Hello-world-ci
        run: echo "HELLO WORLD FROM CI"
